language: python
matrix:
  include:
    - python: 2.7
      dist: xenial
warnings_are_errors: false
sudo: required
cache: pip
install:
  - pip install -r requirements.txt
  - python setup.py -q install
script:
  - travis_wait 35 python -m unittest discover
